import esbuild from "esbuild";
import process from "process";
import builtins from "builtin-modules";

const banner =
`/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
// Reset yjs's "already imported" globalThis flag set by any prior load of
// this bundle. Obsidian's disable/enable cycle re-evaluates our code in the
// same renderer process, which would otherwise have yjs.cjs log a red
// console.error about duplicate import. The check is just guarding against
// instanceof breakage across yjs versions — irrelevant here since we always
// ship the same bundled yjs.
if (typeof globalThis !== "undefined" && globalThis["__ $YJS$ __"]) {
  delete globalThis["__ $YJS$ __"];
}
`;

const prod = (process.argv[2] === "production");

const context = await esbuild.context({
	banner: { js: banner },
	entryPoints: ["src/main.ts"],
	bundle: true,
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		...builtins,
	],
	format: "cjs",
	target: "es2018",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	outfile: "main.js",
	minify: prod,
});

if (prod) {
	await context.rebuild();
	process.exit(0);
} else {
	await context.watch();
}
